status: wip
context:
  captions: ['Specialist labs', 'HDTV studios', 'Theatres', 'A long title to test across multiple lines', 'Exhibition spaces', 'Event spaces', 'Cafes and bars', 'Outdoor spaces', 'Offices', 'Meeting rooms']