name: Title
status: wip
collated: false
context:
  text: 'This is a title'
  background: []
  modifiers: []
  animate: false
handle: title

variants:
  - name: white
    label: "White"
    context:
      background: white
      text: 'This is a white highlighted title'

  - name: digital-blue
    label: "Digital blue"
    context:
      background: digital-blue
      text: 'This is a digital blue highlighted title'

  - name: dark-blue
    label: "Dark blue"
    context:
      background: dark-blue
      text: 'This is a dark blue highlighted title'

  - name: examples
    label: "Examples"