label: Cards
status: ready

variants:
  - name: red
    label: "Theme: Red"
    
  - name: burgundy
    label: "Theme: Burgundy"

  - name: digital-blue
    label: "Theme: Digital blue"

  - name: grey
    label: "Theme: Grey"

  - name: ksp
    label: "KSP (Key Selling Points)"
    status: ready

  - name: ksp-light
    label: "KSP (Light on Dark)"
    status: ready

  - name: with-logo
    label: "With logo"