status: ready
notes: "These require a class of 'feature-link--no-image' or 'feature-link--with-image' as appropriate."
context:
  title: 'Life in Staffordshire'
  image: null
  link: '#'
  body: "Where you live is a big part of your student experience and where you'll meet friends for life."