name: Slab
status: ready
collated: false
context:
  text: 'This is a slab'
  background: []
  modifiers: []
handle: slab

variants:
  - name: offwhite
    label: "Background: Offwhite"
    context:
      background: offwhite
      text: 'This is an offwhite slab'

  - name: dark-blue
    label: "Background: Dark blue"
    context:
      background: dark-blue
      text: 'This is a dark blue slab'

  - name: neon
    label: "Background: Neon"
    context:
      background: neon
      text: 'This is a neon slab'

  - name: digital-blue
    label: "Background: Digital blue"
    context:
      background: digital-blue
      text: 'This is a digital blue slab'

  - name: teal
    label: "Background: Teal"
    context:
      background: teal
      text: 'This is a teal slab'

  - name: pale-blue
    label: "Background: Pale blue"
    context:
      background: pale-blue
      text: 'This is a pale blue slab'
      
  - name: slate
    label: "Legacy: Slate"
    context:
      background: slate
      text: 'Slate slabs will become dark blue'

  - name: bg-knot
    label: "Background: Knot"
    context:
      background: knot
      text: 'This is a slab with background image'

  - name: bg-box-knot
    label: "Background: Box Knot"
    context:
      background: box-knot
      text: 'This is a slab with a box knot background image'